.github/workflows/test.yml
=> ci: add test runner

crates/cairo-lang-dojo/src/lib.rs, crates/cairo-lang-dojo/src/plugin_test_data/system, crates/cairo-lang-dojo/src/query.rs, crates/cairo-lang-dojo/src/system.rs
=> feat: query system

crates/cairo-lang-dojo/src/plugin_test_data/system, crates/cairo-lang-dojo/src/query.rs, crates/cairo-lang-dojo/src/system.rs, lib/query.cairo, lib/world.cairo
=> feat(lib): add query type

Cargo.lock, crates/cairo-lang-dojo/Cargo.toml, crates/cairo-lang-dojo/src/plugin_test_data/system, crates/cairo-lang-dojo/src/query.rs
For #27 Contract addresses
Creating the PR to have discussions here.
=> 27 contract addr

Cargo.lock, Cargo.toml, crates/dojo-language-server/Cargo.toml, crates/dojo-language-server/src/bin/language_server.rs
Implements the dojo language server
- Relies on the corelib under `cairo/corelib`
~ 1 hr
=> feat: language server

Cargo.lock, crates/dojo-cli/src/build.rs, crates/dojo-lang/Cargo.toml, crates/dojo-lang/src/db.rs, crates/dojo-lang/src/plugin.rs, crates/dojo-lang/src/plugin_test.rs, crates/dojo-lang/src/query.rs, crates/dojo-lang/src/system.rs, crates/dojo-language-server/Cargo.toml, crates/dojo-language-server/src/bin/language_server.rs, crates/dojo-project/src/lib.rs, crates/dojo-project/src/test.rs, crates/dojo-test-runner/src/cli.rs
=> feat: expose world config on DojoPlugin

.github/workflows/release.yml
Build and tar binaries based on pushed tag to the repository.
Initially build for macOS x86_64 and linux x86_64 and include:
- dojo
- dojo-indexer
- dojo-language-server
- dojo-test
- prinsma-cli
=> dev: GH Release Action

Cargo.lock, crates/dojo-indexer/Cargo.toml, crates/dojo-indexer/sqlx-data.json
Now it's possible to build the indexer crate without a database connection.
Remember to update the `sqlx-data.json` file every time you add a query or migration. This is done with `DATABASE_URL=... cargo sqlx prepare` (from the indexer crate folder).
=> Setup sqlx offline build

crates/dojo-lang/src/commands/mod.rs, crates/dojo-lang/src/commands/set.rs, crates/dojo-lang/src/manifest.rs, crates/dojo-lang/src/plugin.rs, crates/dojo-lang/src/system.rs
=> Refactor: Include components as system deps in manifest

.vscode/settings.json, crates/dojo-lang/src/plugin.rs, crates/dojo-lang/src/plugin_test_data/system, crates/dojo-lang/src/system.rs
Resolves https://github.com/dojoengine/dojo/issues/156
=> feat: handle if/block/match nodes in system

README.md, crates/dojo-erc/src/erc20/erc20.cairo, crates/dojo-erc/src/erc20/systems.cairo, crates/dojo-lang/src/commands/entity.rs, crates/dojo-lang/src/commands/mod.rs, crates/dojo-lang/src/plugin_test_data/system, examples/src/systems.cairo
@ponderingdemocritus do you mind updating the book to reflect the changes here?
=> refactor: update command naming

Cargo.lock, Cargo.toml, crates/dojo-cli/src/migrate.rs, crates/dojo-lang/Cargo.toml, crates/dojo-lang/src/manifest.rs, crates/dojo-project/Cargo.toml, crates/dojo-project/src/lib.rs, crates/dojo-project/src/migration.rs, crates/dojo-project/src/migration/mod.rs, crates/dojo-project/src/migration/world.rs
- moved the migration logic to `dojo-project`
- `World::prepare_for_migration` evaluates what classes/contracts that should be (re)declared/deployed and puts it in `WorldMigration`
=> feat: migration

crates/dojo-lang/src/manifest.rs
No guarantee that `components` and `systems` will yield the same number of items. `zip` will only iterate over the smallest length of the two arrays, leaving the rest of the items in the larger array untouched.
=> fix: remove `zip` for iterating over systems and components

.github/workflows/ci.yml
Updating the CI checkout action from v2 to v3
=> ci: use v3 of checkout action

crates/dojo-core/src/storage/query.cairo
commit-id:f9d4b1df
---
**Stack**:
- #223
- #222 ⬅
- #221
=> Expose storage domain on query

.spr.yml, crates/dojo-core/src/storage/index.cairo, crates/dojo-core/src/storage/kv.cairo, crates/dojo-core/src/storage/query.cairo
=> Cache computed query key

crates/dojo-lang/src/commands/entities.rs, crates/dojo-lang/src/commands/set.rs, crates/dojo-lang/src/component.rs, crates/dojo-lang/src/plugin_test_data/component, crates/dojo-lang/src/plugin_test_data/system
Resolves #230.
Also removing some unnecessary imports from Components.
=> dev: using fully qualified array path

.vscode/launch.json, README.md, corelib
Hello 🙂 I was working through the dev container setup and ran into some issues with the `dojo-language-server`. I've made some updates on the documentation thinking it might help new contributors when setting things up
=> docs: rename paths and update README

crates/dojo-core/src/interfaces.cairo, crates/dojo-core/src/lib.cairo, crates/dojo-core/src/world_factory.cairo
- world factory contract that deploys an executor and world, then calls the world contract to register all systems and components
since protostar is not yet available in the project, i've done an e2e test on the testnet directly: 
- world factory contract was deployed here: https://testnet.starkscan.co/contract/0x01e9b573ca3004c96b306d965f26425d845f8e2409bd2ecd1352fbafccceada7#overview
- spawn tx here: https://testnet.starkscan.co/tx/0x59c09ee25617e7c30007c29b647c81f341569b960431fe792be9bb532b0e384#overview
=> Implement world factory

crates/dojo-core/src/storage/index.cairo
Calling `Index::delete` does not panic anymore. Small DRY improvements. One more unit test to check for order after deleting from the middle.
=> dev: no panic on deleting non-existing from index

crates/dojo-project/src/lib.rs, crates/dojo-project/src/migration/mod.rs, crates/dojo-project/src/migration/world.rs
since we have katana / madara coming live
=> Switch to RPC

Cargo.lock, crates/dojo-world/Cargo.toml, crates/dojo-world/src/lib.rs, crates/dojo-world/src/manifest.rs, crates/dojo-world/src/manifest_test.rs, crates/dojo-world/src/test_utils.rs
=> Add manifest test + improve error handling

crates/dojo-world/src/manifest.rs, crates/dojo-world/src/manifest_test.rs
commit-id:13f8fef8
---
**Stack**:
- #298 ⬅
- #297
=> Add test for empty world

crates/torii/README.md
=> Readme update

crates/torii/migrations/20230316154230_setup.sql, crates/torii/sqlx-data.json, crates/torii/src/graphql/component.rs, crates/torii/src/graphql/constants.rs, crates/torii/src/graphql/entity.rs, crates/torii/src/graphql/entity_state.rs, crates/torii/src/graphql/event.rs, crates/torii/src/graphql/mod.rs, crates/torii/src/graphql/system.rs, crates/torii/src/graphql/system_call.rs, crates/torii/src/tests/entities_test.rs, crates/torii/src/tests/events_test.rs, crates/torii/src/tests/fixtures/seed.sql
Pagination support for entities/events for now, will generalize that logic in followup PR after we've introduced dynamic schema
=> Graphql pagination support

crates/dojo-core/src/interfaces.cairo
quick fix, seems like the delete_entity interface was removed unintentionally
=> fix: add delete_entity to interface

crates/torii/src/cli.rs
=> update args with default local rpc, and dummy world, remove apibara

Cargo.lock, crates/torii/Cargo.toml, crates/torii/src/graphql/server.rs
Poem framework seem to mesh better with async-graphql lib
=> Indexer graphql api use poem

CONTRIBUTING.md, README.md
- updates readme for clearer get started
- adds contributing guidelines
=> readme update and contrib guide

crates/katana-core/src/starknet/block.rs, crates/katana-core/src/starknet/mod.rs, crates/katana-core/tests/starknet.rs
=> Update `block context` upon `pending` block generation

.all-contributorsrc, README.md
Makes it seem more **_✨contributor-friendly✨._**
=> Add all contributors list

Cargo.lock, crates/katana-rpc/Cargo.toml, crates/katana-rpc/src/lib.rs
=> Katana CORS

crates/torii/src/graphql/component.rs, crates/torii/src/graphql/entity.rs, crates/torii/src/graphql/event.rs, crates/torii/src/graphql/mod.rs, crates/torii/src/graphql/schema.rs, crates/torii/src/graphql/storage.rs, crates/torii/src/graphql/system.rs, crates/torii/src/graphql/system_call.rs, crates/torii/src/graphql/utils/extract_value.rs, crates/torii/src/graphql/utils/mod.rs, crates/torii/src/tests/components_test.rs
Implements storage union for component, so graphql schema with two storage objects (Cash, Stats) would look something like this:
```
type Component {
id: ID!
...
storage: Storage!
}
union Storage = Cash | Stats
type Cash {
amount: u8!
}
type Stats {
health: u8!
mana: u8!
}
```
=> Graphql storage union

crates/torii/src/cli.rs, crates/torii/src/engine.rs, crates/torii/src/indexer.rs
=> Extract indexing engine

Cargo.lock, crates/torii/Cargo.toml, crates/torii/src/cli.rs, crates/torii/src/engine.rs, crates/torii/src/indexer.rs, crates/torii/src/processors/mod.rs, crates/torii/src/state/memory.rs, crates/torii/src/state/mod.rs, crates/torii/src/state/sql.rs
=> Implement indexer

.devcontainer/devcontainer.json
Update container image hash for devcontainer
=> devcontainer: update container image hash

crates/dojo-core/src/test_utils.cairo, crates/dojo-core/tests/src/executor.cairo, crates/dojo-core/tests/src/world.cairo, crates/dojo-core/tests/src/world_factory.cairo, crates/dojo-lang/src/manifest.rs, crates/dojo-lang/src/plugin_test_data/system, crates/dojo-lang/src/system.rs, crates/sozo/src/ops/migration/strategy.rs, examples/ecs/src/systems.cairo
change name in compiler, `manifest.rs`. deleted System using strip_suffix 
#404
=> rm  `System` in manifest file

crates/sozo/src/commands/build.rs, crates/sozo/src/commands/migrate.rs, crates/sozo/src/commands/mod.rs
+ move `ProfileSpec` to another file
=> refactor(sozo): add verbosity flag for `build` cmd

crates/sozo/src/commands/test.rs
Passing CLI args to the test runner when executing `sozo test`
```sh
$ target/release/sozo test examples/ecs -f is_zero
Compiling dojo_examples v0.1.0 (/Users/m/projects/dojo/examples/ecs/Scarb.toml)
running 1 tests
test dojo_examples::components::test_position_is_zero ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 2 filtered out;
Finished release target(s) in 3 seconds
```
=> feat: pass cli args to sozo test

crates/dojo-test-utils/src/sequencer.rs, crates/katana-core/src/sequencer.rs, crates/katana-core/src/starknet/mod.rs, crates/katana-core/tests/starknet.rs, crates/katana/src/cli.rs, crates/katana/src/main.rs
Implement a feature to produce block in an interval. Can be set using the `--block-time` option in the CLI.
=> feat(katana): interval block production

crates/dojo-core/tests/README.md, packages/readme.md
=> Fix: typos

crates/torii/src/graphql/object/component.rs, crates/torii/src/graphql/object/mod.rs, crates/torii/src/graphql/object/storage.rs, crates/torii/src/graphql/schema.rs
An example of a Move component would produce the following queries.
move(id: ID!): Move!
moveList(limit: Int): [Move]
=> Add list suffix to plural storage objects

crates/dojo-world/src/component.rs
Resolves https://github.com/dojoengine/dojo/issues/473
=> Fix sozo incorrect table hash

Cargo.lock, crates/dojo-world/src/manifest.rs, crates/dojo-world/src/manifest_test.rs, crates/dojo-world/src/migration/strategy.rs, crates/dojo-world/src/migration/world.rs, crates/sozo/src/ops/migration/mod.rs
=> fix(sozo): fix world diff computed incorrectly

crates/dojo-world/src/migration/class.rs, crates/dojo-world/src/migration/contract.rs, crates/dojo-world/src/migration/mod.rs, crates/dojo-world/src/migration/strategy.rs, crates/dojo-world/src/migration/world.rs, crates/sozo/src/ops/migration/mod.rs
Resolves #479.
- Displays total number of items to be migrated.
- Migration type; if the items to be migrated is an `Update`/`New` w.r.t to the remote World.
=> refactor(sozo-migrate): general migration improvement

taplo.toml
=> style(toml): allow only 1 blank line

Cargo.toml, taplo.toml
=> build(deps): remove patch redundancy

crates/katana/core/src/sequencer.rs, crates/katana/rpc/src/katana/mod.rs
commit-id:1d11cc55
---
**Stack**:
- #548 ⬅
- #547
=> refactor(katana): remove `KatanaApi` trait impl from `Sequencer`

packages/core/src/network/SyncWorker.ts, packages/core/src/provider/RPCProvider.ts, packages/core/src/provider/provider.ts, packages/core/src/types/index.ts, packages/core/src/utils/index.ts
Small fix in the core dojo package, due to changes in:
- the StoreSetRecord event
- the entities query
=> fix: fixed dojo engine core following latest dojo changes

crates/torii/src/graphql/types.rs
- just changing Address to ContractAddress
=> fix: switch Address to ContractAddress

crates/torii/src/graphql/utils/mod.rs
fix issue with component names that were in pascal case
=> [torii] fix: pascal case type_name

docs/worlds.md
=> doc: update `worlds.md` to the latest version

Cargo.lock, Cargo.toml, crates/katana/core/src/lib.rs
- Update `scarb` git tag
- Rebase `blockifier` and `cairo-vm`
=> build: update deps

crates/katana/core/src/backend/block.rs, crates/katana/core/src/backend/event.rs, crates/katana/core/src/backend/mod.rs, crates/katana/core/src/sequencer.rs, crates/katana/core/src/sequencer_error.rs, crates/katana/core/src/util.rs, crates/katana/rpc/src/starknet.rs
Fixes: #668 
discussion related to this in discord thread: https://discord.com/channels/1062934010722005042/1125377039248142356
=> fix(katana/rpc): return events in chunks with continuation token

index.html
=> chore: 679 landing page improvements

Dockerfile, crates/dojo-core/src/world.cairo
Hi there, this smol pr adds healthcheck for docker
Fix #682
=> feat: add healthcheck docker

packages/core/package.json, packages/core/src/network/SyncWorker.ts, packages/core/src/network/graphql.ts, packages/core/src/utils/index.ts
You can choose if you want to sync the state by either calling the entities view function in the contract, or through the indexer. The latter is useful for Madara as there seems to be an issue currently for calling view functions.
=> [@dojoengine/core] feat: Added sync through  indexer

crates/sozo/src/commands/events.rs, crates/sozo/src/ops/events.rs
=> feat(sozo): take continuation_token as argument

.all-contributorsrc, README.md
- :busts_in_silhouette: Add @ptisserand as a contributor
- :busts_in_silhouette: Add @glihm as a contributor
- :busts_in_silhouette: Add @coostendorp as a contributor
- :busts_in_silhouette: Add @xJonathanLEI as a contributor
- :busts_in_silhouette: Add @neotheprogramist as a contributor
- :busts_in_silhouette: Add @lambda-0x as a contributor
- :busts_in_silhouette: Add @bajpai244 as a contributor
- :busts_in_silhouette: Add @jobez as a contributor
=> chore: add contributors

crates/dojo-erc/src/erc721.cairo, crates/dojo-erc/src/erc721/components.cairo, crates/dojo-erc/src/erc721/erc721.cairo, crates/dojo-erc/src/erc721/lib.cairo, crates/dojo-erc/src/erc721/systems.cairo, crates/dojo-erc/src/lib.cairo
solves https://github.com/dojoengine/dojo/issues/610
TODO
Expose mint/burn function with permission checks?
Create an utils directory in dojo-erc for shared helpers?
=> feat: Added  erc721

crates/torii/src/graphql/object/component_state.rs, crates/torii/src/state/sql.rs, crates/torii/src/tests/common/mod.rs
Resolves https://github.com/dojoengine/dojo/issues/735
=> fix(torii): ignore keys as component members

crates/dojo-erc/Scarb.toml
=> removed target.dojo from scarb.toml

Cargo.lock, Cargo.toml, crates/dojo-world/src/manifest.rs, crates/dojo-world/src/migration/mod.rs, crates/dojo-world/src/utils.rs, crates/katana/core/src/utils/transaction.rs, crates/sozo/src/ops/migration/mod.rs
=> update `starknet-rs` to v0.5.0

Cargo.lock, crates/torii/client/wasm/Cargo.lock, crates/torii/client/wasm/README.md, crates/torii/client/wasm/index.html, crates/torii/client/wasm/worker.js
smol PR to make the example run
=> minor fixes to make example work

packages/core/package.json, packages/core/src/constants/abi.json, packages/core/src/provider/RPCProvider.ts
- adds helper to provider for easy reading of Systems
=> computed read function

Cargo.lock, Cargo.toml, crates/katana/Cargo.toml, crates/katana/core/Cargo.toml, crates/katana/core/src/execution.rs, crates/katana/rpc/Cargo.toml, crates/sozo/Cargo.toml, crates/torii/core/Cargo.toml, crates/torii/graphql/Cargo.toml, crates/torii/server/Cargo.toml
Remove unused and redundant dependencies, plus some code cleaning.
=> chore: remove redundant deps + cleanups

crates/torii/core/src/sql.rs, crates/torii/graphql/src/object/entity.rs
Entities query keys param to match entire composite key rather than partial
=> fix(torii): exact key matching issue

crates/katana/core/src/service.rs
=> fix(katana-core): fix disable fee not working + output execution logs

crates/torii/graphql/src/tests/common/mod.rs, crates/torii/graphql/src/tests/components_test.rs, crates/torii/graphql/src/tests/entities_test.rs, crates/torii/graphql/src/tests/subscription_test.rs
Need to decouple torii graphql tests from ecs example, pending refactor in this pr https://github.com/dojoengine/dojo/pull/818
=> fix(torii): graphql tests failing

crates/katana/core/src/utils/contract.rs
=> fix(katana): invalid compressed class encoding

crates/torii/core/src/engine.rs
The updated sync head was not used, therefore the engine will loop again from the beginning.
I also changed querying the block number using `blockHashAndNumber` instead of `getBlockWithTxs` RPC endpoint.
Added a small check when the current head is equal to the latest block number, to make sure the  processed block will not be processed again.
=> fix(torii-core): engine loop start over for every iteration

Cargo.lock, Cargo.toml, crates/dojo-types/Cargo.toml, crates/dojo-types/src/core.rs
From graphql side, need to be able to iterate over the types and get its corresponding string
=> Update core cairo type

Cargo.lock, crates/katana/core/Cargo.toml, crates/katana/core/src/backend/mod.rs, crates/katana/core/src/sequencer.rs, crates/katana/core/src/service/block_producer.rs, crates/katana/core/src/service/mod.rs, crates/katana/core/tests/sequencer.rs, crates/katana/rpc/src/katana.rs, crates/katana/rpc/src/lib.rs, crates/katana/rpc/src/starknet.rs, crates/katana/src/main.rs, crates/torii/client/wasm/Cargo.lock
commit-id:90847a65
---
**Stack**:
- #942 ⬅
- #941
=> refactor(katana): remove `Sequencer` trait

.github/workflows/cargo-udeps.yml, .github/workflows/ci.yml
adds a separate workflow to run `cargo udeps` weekly.
=> chore(ci): add weekly cargo-udeps

Cargo.toml, crates/dojo-types/src/lib.rs, crates/dojo-types/src/schema.rs, crates/dojo-types/src/system.rs, crates/katana/core/Cargo.toml, crates/torii/client/src/client/error.rs, crates/torii/client/src/client/mod.rs, crates/torii/client/src/client/storage.rs, crates/torii/client/src/client/subscription.rs, crates/torii/client/src/contract/model.rs, crates/torii/client/src/lib.rs, crates/torii/client/src/utils.rs, crates/torii/client/wasm/src/lib.rs, crates/torii/client/wasm/worker.js, crates/torii/grpc/proto/types.proto, crates/torii/grpc/src/conversion.rs, crates/torii/grpc/src/server/mod.rs, crates/torii/grpc/src/server/subscription.rs
Updated subscription server to compute storage addresses correctly.
=> refactor(torii): compute storage addresses correctly in subscription service

crates/torii/core/src/sql.rs
- Use entity_id as primary key of model tables and event_id as separate column. Using event_id as primary was causing new inserts instead of upserting to existing ones.
- Check if model name exists before updating, otherwise graphql returns duplicate results
=> Fix indexer model upsert issue

crates/sozo/src/commands/auth.rs, crates/sozo/src/ops/auth.rs, crates/torii/client/src/contract/world.rs
=> fix: resolves #928 by migrating sozo auth writer to 0.3.0

crates/torii/server/src/server.rs
Resolves: #1003 
- Logging messages at server startup with server address
____
Almost feel bad to push 4 characters but it is how it is, let me know if I can miraculously add more lines. 😎
=> Torii: show server address on init

crates/dojo-lang/src/contract.rs, crates/dojo-lang/src/lib.rs, crates/dojo-lang/src/plugin.rs, crates/dojo-lang/src/plugin_test_data/system, examples/ecs/src/systems/with_decorator.cairo
=> rename #[system] to #[dojo::contract]

crates/dojo-core/src/world.cairo, crates/dojo-lang/src/manifest_test_data/manifest
new:
-WriterUpdated  grant_writer / revoke_writer
-OwnerUpdated : grant_owner / revoke_owner
-ExecutorUpdated : set_executor
-ContractDeployed : deploy_contract
updated:
-ModelRegistered : add a prev_class_hash property =0 on first registration
-update bool constants to true / false
=> feat: add some world events

Cargo.lock, crates/katana/Cargo.toml, crates/katana/src/main.rs
Resolves #1036 
Display `katana` intro messages in JSON.
=> Output `katana` intro as JSON

crates/dojo-core/src/database.cairo, crates/dojo-core/src/world.cairo, crates/dojo-core/src/world_test.cairo, crates/dojo-lang/src/manifest_test_data/manifest
Fixes https://github.com/visoftsolutions/dojo/issues/18
=> Add entity_ids Command to world.cairo to Only Retrieve Entity IDs

Cargo.lock, crates/katana/core/src/service/messaging/service.rs, crates/sozo/src/main.rs, crates/sozo/tests/fixtures/stdout/wrong_cairo_version.stdout, crates/sozo/tests/test_build.rs, crates/sozo/tests/test_data/invalid_cairo_version/Scarb.toml
=> validate cairo compiler version with manifest file

.github/workflows/cargo-udeps.yml, Cargo.lock, crates/dojo-lang/Cargo.toml, crates/torii/client/Cargo.toml, crates/torii/client/wasm/Cargo.lock, crates/torii/core/Cargo.toml, crates/torii/graphql/Cargo.toml, crates/torii/grpc/Cargo.toml, crates/torii/server/Cargo.toml
=> fix: CI and remove unused dependencies

crates/torii/graphql/src/object/model_data.rs, crates/torii/graphql/src/query/constants.rs, crates/torii/graphql/src/query/mod.rs
Fixes issue if model also has member named `entity_id`
=> Fix torii graphql entity_id name conflict

Cargo.lock, crates/dojo-core/Scarb.lock, crates/dojo-core/src/executor_test.cairo, crates/dojo-lang/src/contract.rs, crates/dojo-lang/src/manifest_test_data/manifest, crates/dojo-lang/src/plugin_test_data/system, crates/dojo-world/src/manifest.rs, examples/spawn-and-move/Scarb.lock
=> Rename dojo contract generated name method to dojo_resource

crates/sozo/src/commands/options/starknet.rs
=> fix(sozo): change priority order when fetching rpc url

crates/dojo-lang/src/introspect.rs, crates/dojo-lang/src/plugin_test_data/introspect
=> fix(dojo-lang): wrong type name when deriving `Introspect` for enum

crates/torii/core/src/sql.rs, crates/torii/core/src/types.rs, crates/torii/graphql/src/mapping.rs, crates/torii/graphql/src/object/entity.rs, crates/torii/graphql/src/tests/entities_test.rs, crates/torii/graphql/src/tests/mod.rs, crates/torii/graphql/src/tests/models_test.rs, crates/torii/graphql/src/tests/subscription_test.rs, crates/torii/graphql/src/tests/types-test/Scarb.lock, crates/torii/migrations/20231127235011_entity_model.sql
Remove `model_names` column from entities and added `entity_model` table to better track this relationship.
=> Refactor torii core add entity_model table

Cargo.lock, crates/sozo/Cargo.toml, crates/sozo/src/commands/execute.rs, crates/sozo/src/ops/execute.rs, examples/spawn-and-move/Scarb.lock, examples/spawn-and-move/Scarb.toml
- Updates `sozo execute` to accept the name of the contract rather than the address
closes #1012
=> updates execute to accept name of contract not address

crates/torii/graphql/src/object/inputs/where_input.rs, crates/torii/graphql/src/tests/mod.rs, crates/torii/graphql/src/tests/models_test.rs, crates/torii/graphql/src/tests/types-test/Scarb.lock
=> Pad query values

crates/katana/storage/db/src/codecs.rs, crates/katana/storage/db/src/lib.rs, crates/katana/storage/db/src/mdbx/cursor.rs, crates/katana/storage/db/src/mdbx/mod.rs, crates/katana/storage/db/src/mdbx/tx.rs, crates/katana/storage/db/src/tables.rs
update + add cursor iterator + add docs
=> refactor(katana-db): update mdbx implementations

crates/torii/graphql/src/mapping.rs, crates/torii/graphql/src/object/metadata/mod.rs, crates/torii/graphql/src/query/data.rs, crates/torii/graphql/src/tests/metadata_test.rs, crates/torii/graphql/src/tests/mod.rs
=> Expose world contract address via metadatas connection

crates/torii/grpc/src/server/mod.rs, crates/torii/grpc/src/server/subscriptions/entity.rs
Fix subscribing to specific entities ids not triggering
=> Fix grpc sub entity ids

crates/katana/storage/provider/src/providers/fork/mod.rs, crates/katana/storage/provider/src/providers/in_memory/mod.rs
Fixes #1265 
Will follow up this PR with proper testing
=> fix(katana-provider): take correct amount of tx

Cargo.lock, crates/katana/primitives/src/block.rs, crates/katana/primitives/src/transaction.rs, crates/katana/storage/provider/Cargo.toml, crates/katana/storage/provider/src/providers/in_memory/mod.rs, crates/katana/storage/provider/src/providers/in_memory/state.rs, crates/katana/storage/provider/tests/common.rs, crates/katana/storage/provider/tests/fixtures.rs
A straight forward tests for testing that data is written correctly on every block insertion
=> test(katana-provider): test block insertions for providers

crates/sozo/src/commands/events.rs, crates/sozo/src/ops/events.rs
This PR fixes and enables back the `sozo events` command after being disabled temporarily during Cairo `2.3.0` [update](https://github.com/dojoengine/dojo/pull/1090). 
The command was disable temporarily because a field that was used to get the abi items was made private by Cairo `2.3.0`, but have since forgotten to be updated.
=> fix(sozo): fix `events` command after Cairo `2.3.0` change

crates/katana/runner/src/lib.rs
=> feat(katana): write katana logs to tempdir and print log file path to stderr

crates/katana/src/main.rs, crates/metrics/src/prometheus_exporter.rs, crates/torii/server/src/cli.rs
Torii's metrics are prefixed with "katana_"
=> Fix metrics prefix naming

dojoup/dojoup
- smol change to keep `dojoup` commands all lowercase
=> change casing to be consistent

crates/katana/storage/provider/src/providers/db/mod.rs, crates/katana/storage/provider/src/providers/db/state.rs
=> style(katana-db): include module in table path

Cargo.toml, bin/saya/src/args/mod.rs, bin/saya/src/args/test_saya_config_file.json, crates/saya/core/src/data_availability/celestia/mod.rs, crates/saya/core/src/data_availability/mod.rs, crates/saya/core/src/lib.rs
=> feat(saya): add config file arg for saya bin

crates/torii/core/src/engine.rs, crates/torii/core/src/processors/metadata_update.rs, crates/torii/core/src/processors/mod.rs, crates/torii/core/src/processors/register_model.rs, crates/torii/core/src/processors/store_del_record.rs, crates/torii/core/src/processors/store_set_record.rs, crates/torii/core/src/processors/store_transaction.rs, crates/torii/core/src/sql.rs, crates/torii/migrations/20240207171639_add_txn_type.sql
Closes https://github.com/dojoengine/dojo/issues/1422
=> [Torii] Index more transaction types

dojoup/dojoup
Related to https://github.com/dojoengine/dojo/issues/1604.
=> feat: dojoup - add a welcome message

Cargo.lock, crates/katana/executor/Cargo.toml, crates/katana/executor/src/implementation/blockifier/state.rs, crates/katana/executor/src/implementation/sir/mod.rs, crates/katana/executor/src/implementation/sir/state.rs, crates/katana/executor/tests/executor.rs, crates/katana/executor/tests/fixtures/mod.rs, crates/katana/executor/tests/simulate.rs
- add tests for each executor's `CachedState`
- improve test in `executor.rs`
- fix `sir` not enough gas error
- fix test in `simulate.rs`
=> test(katana-executor): improve tests and add test for state

bin/sozo/src/commands/test.rs, examples/spawn-and-move/Scarb.toml
=> fix(sozo): ensure warnings don't stop tests build

bin/sozo/src/ops/migration/mod.rs, crates/dojo-world/src/manifest.rs, examples/spawn-and-move/manifests/deployments/KATANA.toml
fix: #748
should be merged after merging #1652
=> feat(sozo): add seed to manifest

bin/sozo/src/ops/migration/mod.rs
=> fix(sozo): don't upload to ipfs if in offline mode

Cargo.lock, bin/katana/src/main.rs, crates/katana/rpc/rpc/Cargo.toml, crates/katana/rpc/rpc/src/lib.rs, crates/katana/rpc/rpc/src/metrics.rs
=> feat(katana-rpc): rpc server metrics

crates/torii/core/src/engine.rs
=> fix: duplicate indexation of transactions

crates/torii/client/src/client/mod.rs, crates/torii/libp2p/src/client/mod.rs
changes signatures of libp2p functions to be non mutable
=> refactor: non mutable self references on libp2p 

crates/torii/graphql/src/object/entity.rs, crates/torii/graphql/src/object/event_message.rs, crates/torii/graphql/src/tests/entities_test.rs
=> fix(torii): query models

crates/katana/primitives/Cargo.toml
forgot to enable `serde` feature on `alloy-primitives` in `katana-primitives`'s `serde` feature
ref #1693
=> fix(katana-primitives): enable `alloy-primitives`'s serde on `serde` feature

Cargo.lock, bin/sozo/Cargo.toml, bin/sozo/src/commands/migrate.rs, crates/katana/rpc/rpc/tests/torii.rs
Closes #1780.
Ensure the targeted network support the correct starknet RPC specification.
=> feat: add verification of the RPC version

crates/dojo-test-utils/Cargo.toml, crates/katana/core/Cargo.toml, crates/katana/rpc/rpc-api/Cargo.toml, crates/katana/rpc/rpc-types-builder/Cargo.toml, crates/katana/rpc/rpc-types/Cargo.toml, crates/katana/rpc/rpc/Cargo.toml, crates/katana/storage/codecs/Cargo.toml, crates/katana/storage/db/Cargo.toml, crates/katana/storage/provider/Cargo.toml
just tidying up the deps on Katana
=> chore(katana): use deps from workspace

.github/workflows/release-dispatch.yml
Makes it a bit easier to use the action
=> Strip version v prefix with release-dispatch

crates/dojo-bindgen/src/plugins/typescript/mod.rs, crates/dojo-bindgen/src/plugins/unity/mod.rs
addresses #1804 and fixes duplicate definitions of tokens referenced by models
=> fix(dojo-bindgen): typescript code gen

crates/katana/docs/database.md
add the changes from #1773, #1774
=> docs(katana): update DB er diagram

Cargo.lock, Cargo.toml, crates/katana/core/Cargo.toml, crates/katana/core/src/service/messaging/ethereum.rs
Bump alloy to 0.7.0
resolves #1871
=> Bump alloy to 0.7.0

bin/katana/src/args.rs, crates/dojo-test-utils/src/sequencer.rs, crates/katana/rpc/rpc/src/config.rs, crates/katana/rpc/rpc/src/lib.rs
=> feat: add allowed-origins to katana cli

crates/torii/core/src/engine.rs
=> feat: sync range marks pending cursor to none

Cargo.lock, Cargo.toml, crates/saya/core/Cargo.toml
=> Update Saya to use rustls-tls rather than openssl

dojoup/dojoup
To simplify the getting started docs
=> Handle scarb install in dojoup

crates/katana/primitives/src/transaction.rs
=> Add doc comments for `L1HandlerTx`

README.md
Getting Started Link was broken.
=> Update README.md - Getting Started Link

crates/torii/core/src/engine.rs
=> refactor(torii-core): fix double pending indexing & use btreemap for sorted blocks

.github/workflows/release.yml
=> fix: ensure pkg-config is also installed

crates/torii/core/src/sql.rs
=> fix(torii): fix table name using reserved sql keywords

.github/workflows/ci.yml, Cargo.lock, crates/saya/core/Cargo.toml
=> fix(ci): ensure katana runs in debian:bookworm-slim

crates/dojo-types/src/schema.rs, crates/torii/core/src/sql.rs, crates/torii/graphql/src/object/entity.rs, crates/torii/graphql/src/query/mod.rs
=> fix(torii): handle array of unknown enum variants and empty arrays

Cargo.lock, bin/sozo/Cargo.toml, bin/sozo/src/commands/options/account/mod.rs, bin/sozo/src/commands/options/account/type.rs, bin/sozo/src/commands/options/signer.rs
=> refactor(sozo): use a wrapper type as the concrete account type

Cargo.lock, Cargo.toml, bin/sozo/Cargo.toml, bin/sozo/src/commands/auth.rs, bin/sozo/src/commands/execute.rs, bin/sozo/src/commands/migrate.rs, bin/sozo/src/commands/options/account/controller.rs, bin/sozo/src/commands/options/account/mod.rs, bin/sozo/src/commands/options/account/type.rs, bin/sozo/src/commands/register.rs, bin/sozo/src/utils.rs
=> feat(sozo): add Cartridge's Controller-based account 

Cargo.lock, crates/torii/libp2p/Cargo.toml
use rev for libp2p dependencies
=> chore(torii-libp2p): use rev

crates/torii/grpc/src/server/mod.rs, crates/torii/grpc/src/server/tests/entities_test.rs
Implements the composite gRPC query
#1613
=> feat(torii-grpc): composite query

bin/sozo/tests/register_test.rs, crates/dojo-lang/src/plugin_test_data/system, crates/dojo-world/src/manifest/manifest_test.rs, crates/dojo-world/src/metadata_test.rs, crates/dojo-world/src/migration/world_test.rs, crates/sozo/ops/src/tests/migration.rs, crates/sozo/ops/src/tests/setup.rs, crates/torii/client/src/client/storage.rs, crates/torii/client/src/client/subscription.rs, crates/torii/core/src/sql_test.rs, crates/torii/graphql/src/tests/mod.rs, crates/torii/graphql/src/tests/subscription_test.rs, crates/torii/grpc/src/server/tests/entities_test.rs
Due to wasm32 specificities, this PR added tests to code already pushed in the namespace branch to ensure CI runs well.
=> fix: test fixes for wasm32 changes

Cargo.lock
the rev include this PR https://github.com/dojoengine/blockifier/pull/9
=> Bump `blockifier` to latest rev

crates/torii/core/src/processors/store_set_record.rs, crates/torii/core/src/sql_test.rs
=> fix(torii/processor): flush the queue for store_set_record

scripts/compare-torii-data.py
**Stack**:
- #2470 ⬅
- #2451
- #2449
- #2448
- #2447
- #2444
- #2442
=> feat(torii): add a script to verify data

crates/dojo/test-utils/src/sequencer.rs, crates/katana/cli/src/args.rs, crates/katana/cli/src/options.rs, crates/katana/core/src/backend/mod.rs, crates/katana/node/src/config/rpc.rs, crates/katana/node/src/lib.rs, crates/katana/rpc/rpc-types/src/error/starknet.rs, crates/katana/rpc/rpc-types/src/trie.rs, crates/katana/rpc/rpc/src/starknet/config.rs, crates/katana/rpc/rpc/src/starknet/mod.rs, crates/katana/rpc/rpc/tests/proofs.rs
=> feat(katana): limit number of proof keys
